In [25]:
import torch
from client import client
from model import LogisticRegression

class ARGS(object):
    def __init__(self):
        pass

args = ARGS
args.epochs=3
args.datapath = '../fedavg_attmpt/data/'
model = LogisticRegression(4,3)

worker1 = client(1,1,model,args)

In [9]:
worker1.train()

In [10]:
worker1.send_pseudo_grad()

{'linear.weight': tensor([[ 1.4619e-02,  5.4656e-03,  1.3410e-02,  4.4873e-03],
         [-1.3918e-02, -5.5404e-03, -1.2263e-02, -4.0332e-03],
         [-7.0131e-04,  7.4819e-05, -1.1475e-03, -4.5416e-04]]),
 'linear.bias': tensor([ 2.1700e-03, -2.1182e-03, -5.1811e-05])}

In [11]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[-0.0076,  0.0751,  0.0168, -0.1027],
                      [-0.0435, -0.2942,  0.0199, -0.2675],
                      [-0.4540, -0.1180,  0.1120, -0.3506]])),
             ('linear.bias', tensor([-0.2377,  0.3823, -0.1655]))])

In [12]:
worker1.eval()


(5, 10)

In [13]:
worker1.optimizer()

TypeError: 'SGD' object is not callable

In [14]:
for (param_name,param) in worker1.model.state_dict().items():
    print(param_name,param)

linear.weight tensor([[-0.0076,  0.0751,  0.0168, -0.1027],
        [-0.0435, -0.2942,  0.0199, -0.2675],
        [-0.4540, -0.1180,  0.1120, -0.3506]])
linear.bias tensor([-0.2377,  0.3823, -0.1655])


In [15]:
param.grad = torch.ones_like(param)
param.grad

tensor([1., 1., 1.])

In [16]:
from server import server

ImportError: cannot import name 'server' from 'server' (/mnt/c/Users/lpott/Desktop/RPC_Tutorial/fedopt_attmpt/server.py)

In [17]:
dic = {"a":[1,2,3],"b":[2,3,2]}
for j,k in {"a":[1,2,3],"b":[2,3,2]}.items():
    k.append(2)
print(dic)

{'a': [1, 2, 3], 'b': [2, 3, 2]}


In [18]:
worker1.model['linear.1']

TypeError: 'LogisticRegression' object is not subscriptable

In [24]:
worker1.model.get_parameter('linear.weight').grad

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
worker1.model.get_parameter('linear.weight').grad = torch.zeros_like(worker1.model.get_parameter('linear.weight'))

In [34]:
from sklearn.datasets import fetch_openml
dataset = fetch_openml("mnist_784")

In [42]:
dataset.data
dataset.target.astype(int).tolist()

[5,
 0,
 4,
 1,
 9,
 2,
 1,
 3,
 1,
 4,
 3,
 5,
 3,
 6,
 1,
 7,
 2,
 8,
 6,
 9,
 4,
 0,
 9,
 1,
 1,
 2,
 4,
 3,
 2,
 7,
 3,
 8,
 6,
 9,
 0,
 5,
 6,
 0,
 7,
 6,
 1,
 8,
 7,
 9,
 3,
 9,
 8,
 5,
 9,
 3,
 3,
 0,
 7,
 4,
 9,
 8,
 0,
 9,
 4,
 1,
 4,
 4,
 6,
 0,
 4,
 5,
 6,
 1,
 0,
 0,
 1,
 7,
 1,
 6,
 3,
 0,
 2,
 1,
 1,
 7,
 9,
 0,
 2,
 6,
 7,
 8,
 3,
 9,
 0,
 4,
 6,
 7,
 4,
 6,
 8,
 0,
 7,
 8,
 3,
 1,
 5,
 7,
 1,
 7,
 1,
 1,
 6,
 3,
 0,
 2,
 9,
 3,
 1,
 1,
 0,
 4,
 9,
 2,
 0,
 0,
 2,
 0,
 2,
 7,
 1,
 8,
 6,
 4,
 1,
 6,
 3,
 4,
 5,
 9,
 1,
 3,
 3,
 8,
 5,
 4,
 7,
 7,
 4,
 2,
 8,
 5,
 8,
 6,
 7,
 3,
 4,
 6,
 1,
 9,
 9,
 6,
 0,
 3,
 7,
 2,
 8,
 2,
 9,
 4,
 4,
 6,
 4,
 9,
 7,
 0,
 9,
 2,
 9,
 5,
 1,
 5,
 9,
 1,
 2,
 3,
 2,
 3,
 5,
 9,
 1,
 7,
 6,
 2,
 8,
 2,
 2,
 5,
 0,
 7,
 4,
 9,
 7,
 8,
 3,
 2,
 1,
 1,
 8,
 3,
 6,
 1,
 0,
 3,
 1,
 0,
 0,
 1,
 7,
 2,
 7,
 3,
 0,
 4,
 6,
 5,
 2,
 6,
 4,
 7,
 1,
 8,
 9,
 9,
 3,
 0,
 7,
 1,
 0,
 2,
 0,
 3,
 5,
 4,
 6,
 5,
 8,
 6,
 3,
 7,
 5,
 8,
 0,
 9,
 1,
 0,
